export type Lesson={concepts:[string,string][];projects:string[];hire:string};
const x=(concepts:[string,string][],projects:string[],hire:string):Lesson=>({concepts,projects,hire});
export const lessons:Record<string,Lesson>={
python:x([["Dynamic typing","Types are checked at runtime, so tests matter."],["Virtual environments","Isolate each project's packages with venv."],["Generators & async","Handle big data and I/O lazily."]],["CLI that cleans a CSV","REST API with FastAPI"],"Show a deployed API plus one data project."),
javascript:x([["Event loop","One thread runs queued callbacks from timers, I/O and promises."],["Promises & async/await","Non-blocking code that reads top to bottom."],["Closures","Functions remember the variables around them."]],["Interactive to-do app","Weather dashboard using fetch"],"Ship small live apps and explain the event loop."),
typescript:x([["Static types","Describe data shapes so editors catch bugs early."],["Generics","Reusable code that keeps type safety."],["Narrowing","Checks that tell the compiler the exact type."]],["Convert a JS project to TS","Typed API client"],"Most frontend roles list it; use strict mode."),
cpp:x([["Manual memory","You allocate and free; leaks and dangling pointers are your risk."],["RAII","Tie cleanup to object lifetime via smart pointers."],["STL","Vectors, maps and algorithms over hand-rolled loops."]],["Terminal Snake game","Simple memory allocator"],"Show performance-minded projects."),
rust:x([["Ownership","Each value has one owner and is freed with it."],["Borrowing","References read or mutate without owning, checked at compile time."],["Traits","Shared behaviour across types."]],["grep clone CLI","Small web server"],"Open-source contributions stand out."),
go:x([["Goroutines","Lightweight threads run by the runtime."],["Channels","Pass data between goroutines safely."],["Error values","Errors are returned, not thrown."]],["Concurrent URL checker","REST service with Postgres"],"Cloud teams value small reliable services."),
java:x([["OOP","Model software with classes and interfaces."],["JVM & GC","Code runs on the JVM, which frees memory."],["Collections & streams","Lists, maps and stream pipelines."]],["Library API with Spring Boot","Console bank simulator"],"Know Spring Boot, SQL and testing."),
csharp:x([["Types & OOP","Strongly typed classes, records, interfaces."],["LINQ","Declarative queries over collections."],["async/await","Task-based non-blocking I/O."]],["ASP.NET Core Web API","Unity mini-game"],"Pair C# with Azure and SQL Server."),
sql:x([["JOINs","Combine rows from related tables by key."],["Indexes","Speed up reads, slow down writes."],["Transactions","Group changes so all succeed or none (ACID)."]],["Design a shop schema","Analytics queries on a public dataset"],"Expect live joins and window functions."),
swift:x([["Optionals","A value is present or nil; the compiler makes you handle both."],["ARC","Automatic reference counting frees unused objects."],["SwiftUI","UI as a function of state."]],["Habit tracker app","Weather app with an API"],"Publish an app to the App Store."),
kotlin:x([["Null safety","Types say whether null is allowed."],["Coroutines","Async code without callback hell."],["Data classes","One line gives equals, copy, toString."]],["Notes app in Jetpack Compose","Ktor REST API"],"Android roles expect Kotlin and Compose."),
php:x([["Request lifecycle","Each request runs a script and returns a response."],["Composer","Dependency manager for packages."],["Laravel","Framework with routing, ORM and auth."]],["Blog with Laravel","Validated contact form"],"Show real sites; WordPress and Laravel gigs are common."),
dart:x([["Null safety","The compiler tracks nullable types."],["Widgets","Flutter UIs are trees of widgets."],["Futures & isolates","Async work and separate-memory concurrency."]],["Flutter to-do app","App using a public API"],"Show one app on both Android and iOS."),
robotics:x([["Control loop","Read sensors, decide, drive motors, repeat fast."],["ROS 2","Nodes publish and subscribe to topics."],["Sensor integration","Filter noisy readings before acting."]],["Arduino line follower","ESP32 sensor logger"],"Videos of working hardware beat résumés."),
testing:x([["Test pyramid","Many unit, fewer integration, few E2E tests."],["Mocking","Replace dependencies to isolate what you test."],["CI automation","Run tests on every push."]],["Add Jest tests to a project","Playwright login test"],"Show a repo with tests in GitHub Actions."),
databases:x([["Relational modeling","Tables, keys and normalisation keep data consistent."],["Caching","Redis keeps hot data in memory."],["Vector search","Embeddings find similar text or images."]],["Todo API on PostgreSQL","Semantic search with embeddings"],"Explain when to pick SQL, NoSQL or cache."),
devops:x([["Containers","Docker bundles an app with its dependencies."],["Orchestration","Kubernetes schedules and heals containers."],["Observability","Logs, metrics and alerts show what broke."]],["Dockerise an app","CI/CD pipeline to a cloud VM"],"A deployed project beats certificates alone."),
"market-insights":x([["Skill matrices","Map roles to the skills they list."],["Remote hiring","Competition is global; portfolios matter."],["Compensation data","Compare several surveys; ranges vary by region."]],["Analyse job postings in your region","Personal skill-gap table"],"Tailor your stack to postings you actually see."),
"software-houses":x([["Agile sprints","Short cycles deliver working software often."],["Code review","Peers check changes before merging."],["Client communication","Clear estimates and updates build trust."]],["Run a mock sprint with friends","Write a project proposal"],"Show teamwork: pull requests and reviews."),
business:x([["MRR & churn","Recurring revenue and customers lost per month."],["Product-market fit","Users would be upset if it vanished."],["MVP","Smallest version testing your riskiest assumption."]],["Landing page to validate an idea","Unit economics for a SaaS"],"Show ship-and-measure habits.")};
